### ISSUE TITLE
(grafana) warning with daily & apr

### ISSUE THREAD

**Issue by enzofoucaud** [enzofoucaud/dockmas#1]
Daily & APR have a warning, how to solve it ?

![image](https://github.com/enzofoucaud/dockmas/assets/15039645/f2970bde-0259-4bd1-bb3e-5b4b8699e13d)

**Comment by BapRx** [comment]
I switched to these PromQL expressions instead:

APR (%)
`(176256 * (sum(massa_getadd_roll_final_roll) / sum(rolls)) * 365) / sum(massa_getadd_roll_final_roll)`

Daily ($MASSA)
`176256 * sum(massa_getadd_roll_final_roll) / sum(rolls)`

**Comment by enzofoucaud** [comment]
> I switched to these PromQL expressions instead:
> 
> APR (%) `(176256 * (sum(massa_getadd_roll_final_roll) / sum(rolls)) * 365) / sum(massa_getadd_roll_final_roll)`
> 
> Daily ($MASSA) `176256 * sum(massa_getadd_roll_final_roll) / sum(rolls)`

Could you do a PR?

**Comment by BapRx** [comment]
Here you go: https://github.com/enzofoucaud/dockmas/pull/5
