### ISSUE TITLE
A few panels have stopped receiving data

### ISSUE THREAD

**Issue by drphero** [enzofoucaud/dockmas#4]
Active cycle, Connections, and Peers started showing "No data" today. All the others are working well. Tried a restart of the containers, but no luck.
![2024-01-20_22-03](https://github.com/enzofoucaud/dockmas/assets/14174687/380235b6-4540-4159-837e-5dd7beec9b96)

**Comment by enzofoucaud** [comment]
> Active cycle, Connections, and Peers started showing "No data" today. All the others are working well. Tried a restart of the containers, but no luck. ![2024-01-20_22-03](https://private-user-images.githubusercontent.com/14174687/298307617-380235b6-4540-4159-837e-5dd7beec9b96.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MDYwMDczODEsIm5iZiI6MTcwNjAwNzA4MSwicGF0aCI6Ii8xNDE3NDY4Ny8yOTgzMDc2MTctMzgwMjM1YjYtNDU0MC00MTU5LTgzN2UtNWRkN2JlZWM5Yjk2LnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDAxMjMlMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQwMTIzVDEwNTEyMVomWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPTk1MDkwYzFkM2E1ZmFkNGYxOTQ5MTU3ZmQ5ZGNiZTUzYjdiMzE4NzA1NzQ1NjcwOGZjNTQ5NjViZGY5NTM4NzYmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0JmFjdG9yX2lkPTAma2V5X2lkPTAmcmVwb19pZD0wIn0.8-alYN4k3GzqG3zDFYO5-c5l7D8-hz_-NWUQD1trGRM)

Is the error still there?

**Comment by drphero** [comment]
> > Active cycle, Connections, and Peers started showing "No data" today. All the others are working well. Tried a restart of the containers, but no luck. ![2024-01-20_22-03](https://private-user-images.githubusercontent.com/14174687/298307617-380235b6-4540-4159-837e-5dd7beec9b96.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MDYwMDczODEsIm5iZiI6MTcwNjAwNzA4MSwicGF0aCI6Ii8xNDE3NDY4Ny8yOTgzMDc2MTctMzgwMjM1YjYtNDU0MC00MTU5LTgzN2UtNWRkN2JlZWM5Yjk2LnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDAxMjMlMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQwMTIzVDEwNTEyMVomWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPTk1MDkwYzFkM2E1ZmFkNGYxOTQ5MTU3ZmQ5ZGNiZTUzYjdiMzE4NzA1NzQ1NjcwOGZjNTQ5NjViZGY5NTM4NzYmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0JmFjdG9yX2lkPTAma2V5X2lkPTAmcmVwb19pZD0wIn0.8-alYN4k3GzqG3zDFYO5-c5l7D8-hz_-NWUQD1trGRM)
> 
> Is the error still there?

Yes, this is still happening.

**Comment by enzofoucaud** [comment]
> > > Active cycle, Connections, and Peers started showing "No data" today. All the others are working well. Tried a restart of the containers, but no luck. ![2024-01-20_22-03](https://private-user-images.githubusercontent.com/14174687/298307617-380235b6-4540-4159-837e-5dd7beec9b96.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MDYwMDczODEsIm5iZiI6MTcwNjAwNzA4MSwicGF0aCI6Ii8xNDE3NDY4Ny8yOTgzMDc2MTctMzgwMjM1YjYtNDU0MC00MTU5LTgzN2UtNWRkN2JlZWM5Yjk2LnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDAxMjMlMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQwMTIzVDEwNTEyMVomWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPTk1MDkwYzFkM2E1ZmFkNGYxOTQ5MTU3ZmQ5ZGNiZTUzYjdiMzE4NzA1NzQ1NjcwOGZjNTQ5NjViZGY5NTM4NzYmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0JmFjdG9yX2lkPTAma2V5X2lkPTAmcmVwb19pZD0wIn0.8-alYN4k3GzqG3zDFYO5-c5l7D8-hz_-NWUQD1trGRM)
> > 
> > 
> > Is the error still there?
> 
> Yes, this is still happening.

Are there any errors in Prometheus?

**Comment by drphero** [comment]
@enzofoucaud  The prometheus logs seem to be filled with nothing except lines like this
`prometheus  | ts=2024-01-25T22:47:02.702Z caller=notifier.go:530 level=error component=notifier alertmanager=http://alertmanager:9093/api/v2/alerts count=1 msg="Error sending alert" err="Post \"http://alertmanager:9093/api/v2/alerts\": dial ^Cookup alertmanager on 127.0.0.11:53: server misbehaving"`

**Comment by drphero** [comment]
Just did a complete removal of dockmas including the associated volumes and redid the setup. Now it looks like this.

![2024-01-31_17-44](https://github.com/enzofoucaud/dockmas/assets/14174687/2fcbbc85-d2db-443a-ab23-6da0953b543a)

**Comment by drphero** [comment]
I checked the api calls with postman and everything seemed to be fine. After wiping and setting up two more times, it seems to be working again. I still don't know why it initially worked then stopped, but hopefully it doesn't happen again.
